version: '3.7'

services:
    flaskapp:
        build: ./flaskapp-docker
        container_name: flaskapp
        networks:
            - backend
    
    flaskapp:
        build: ./flaskapp-docker
        container_name: wwwflaskapp
        networks:
            - backend

    nginx:
        build: ./nginx
        container_name: ngninx
        environment: 
            - SERVER_NAME=52.52.248.228
        ports:
            - "80:80"
        restart: always
        networks:
            - backend

networks:
    backend: 
        driver: bridge




        

        

