version: '3.7'

services:
    flaskapp:
        build: ./flaskapp-docker
        container_name: flaskapp

    nginx:
        build: ./nginx
        container_name: ngninx
        environment: 
            - SERVER_NAME=52.52.248.228
        ports:
            - "80:80"
        restart: always

networks:
    default:
        driver: bridge




        

        

